name: XII-Days
version: ${version}
main: com.mceteams.xii.XiiPlugin
api-version: '26.2'
description: XII Days Plugin
commands:
  xii:
    description: Commande principale XII Days
    usage: /xii <command>
  join:
    description: Rejoindre une équipe
    usage: /join <COULEUR>
  leave:
    description: Quitter son équipe
    usage: /leave
permissions:
  xii.admin:
    description: Permission admin XII Days
    default: op
  xii.play:
    description: Permission de jouer
    default: true